//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXGuard.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EXGuard.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        ///&lt;Document Version=&quot;2&quot;&gt;
        ///	&lt;!--Removed Packer Options: 69832--&gt;
        ///	&lt;!--Packer Options: 70088--&gt;
        ///    &lt;Protection InputFileName=&quot;dlldir&quot; Options=&quot;70088&quot; OutputFileName=&quot;dlloutdir&quot;&gt;
        ///        &lt;Messages /&gt;
        ///        &lt;Folders /&gt;
        ///        &lt;Objects&gt;
        ///            &lt;Object Type=&quot;Segment&quot; Name=&quot;.text&quot; /&gt;
        ///            &lt;Object Type=&quot;Segment&quot; Name=&quot;.rsrc&quot; /&gt;
        ///            &lt;Object Type=&quot;Segment&quot; Name=&quot;.reloc&quot; /&gt;
        ///        &lt;/Objects&gt;
        ///    &lt;/Protection&gt;
        ///    &lt;DLLBox&gt;
        ///        &lt;Folders /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VMProj {
            get {
                return ResourceManager.GetString("VMProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] VMProtect_Con {
            get {
                object obj = ResourceManager.GetObject("VMProtect_Con", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
